version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    ignore:
      - dependency-name: '@types/node'
        # For @types/node, ignore all updates for version non LTS version
        versions: ['13.x']
    reviewers:
      - 'vazra'
    labels:
      - 'dependencies'
    open-pull-requests-limit: 5
